version: '3.1'

services:
    mysql:
        container_name: mysql
        platform: linux/x86_64
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'kotlin_demo'
        ports:
            - '3306:3306'
        expose:
            - '3306'

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        depends_on:
            - 'mysql'
        links:
            -  'mysql'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - '8183:80'
