package microservice.dungeon.game.aggregates.round.domain

enum class RoundStatus {
    COMMAND_INPUT_STARTED,
    COMMAND_INPUT_ENDED,
    BLOCKING_COMMANDS_DISPATCHED,
    TRADING_COMMANDS_DISPATCHED,
    MOVEMENT_COMMANDS_DISPATCHED,
    BATTLE_COMMANDS_DISPATCHED,
    MINING_COMMANDS_DISPATCHED,
    SCOUTING_COMMANDS_DISPATCHED,
    ROUND_ENDED
}