package microservice.dungeon.game.aggregates.round.domain

enum class RoundStatus {
    COMMAND_INPUT_STARTED,
    COMMAND_INPUT_ENDED,
    BLOCKING_COMMANDS_DISPATCHED,
    SELLING_COMMANDS_DISPATCHED,
    BUY_COMMANDS_DISPATCHED,
    MOVEMENT_ITEM_USE_COMMANDS_DISPATCHED,
    MOVEMENT_COMMANDS_DISPATCHED,
    BATTLE_ITEM_USE_COMMANDS_DISPATCHED,
    BATTLE_COMMANDS_DISPATCHED,
    MINING_COMMANDS_DISPATCHED,
    REPAIR_ITEM_USE_COMMANDS_DISPATCHED,
    REGENERATING_COMMANDS_DISPATCHED,
    ROUND_ENDED
}