# This is a basic workflow to help you get started with Actions

name: Unit Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - 'devops'

jobs:
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup JDK 11 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Unit-Test
        run: |
          mvn test
          echo "-------------------------------------------------------"
          ls -a ./
          echo "-------------------------------------------------------"
          ls -a ./src/test/
          echo "-------------------------------------------------------"
          ls -a ./src/test/kotlin/microservice/dungeon/game/
