# This is a basic workflow to help you get started with Actions

name: Unit Test + Image

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - 'main'
jobs:

  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup JDK 11 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Unit-Test
        run: mvn test
        
  build-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: unit-test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup JDK 11 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build to GitHub Container Registry
        # use jib plugin to build docker image
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build -Dimage=ghcr.io/the-microservice-dungeon/game/gameservice
  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: stop-pull-run
        uses: appleboy/ssh-action@master
        env:
          SERVICE_NAME: devops
        with:
          host: cides03.gm.fh-koeln.de
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PWD }}
          port: 22
          envs: SERVICE_NAME
          script: |
            echo ${{ secrets.PROD_PWD }} | sudo -S docker-compose -f $SERVICE_NAME/service-compose.yml pull
            echo ${{ secrets.PROD_PWD }} | sudo -S docker-compose -f $SERVICE_NAME/service-compose.yml up -d
